### ISSUE TITLE
beefbox.rb :: Please specify the BeEF installation path (Kali)

### ISSUE THREAD

**Issue by treed593** [evilsocket/bettercap-proxy-modules#1]
When running bettercap --proxy --proxy-module=beefbox.rb I get a prompt to specify the BeEF installation path. When I do, no matter what I enter I get the prompt again and am unable to make the script work

**Comment by evilsocket** [comment]
because the path you're passing is not valid, does the "beef" file exist in the path you are using?

**Comment by treed593** [comment]
I misunderstood the prompt, and was entering the full path (including the executable name). Thanks for your help. Awesome project!

**Comment by evilsocket** [comment]
:+1:

**Comment by TedKaczynski** [comment]
evilsocket where can more information about the project? very much this project [Bettercap] Thaks

**Comment by evilsocket** [comment]
@TedKaczynski this is not the place to ask for infos.

**Comment by TedKaczynski** [comment]
very thanks... @evilsocket
