### ISSUE TITLE
beefbox.rb

### ISSUE THREAD

**Issue by daltonspider** [evilsocket/bettercap-proxy-modules#16]
So good job man!!... 
Sorry my poor knowledge  in ruby,
Where exactly I put beef installation path in rb code ? my beef is on "/opt/beef-project/beef.rb" 

 def self.on_options(opts)
    opts.on( '--beef-path PATH', 'Path to the BeEF installation.' ) do |v|
      @@beefpath = File.expand_path v
      unless Dir.exists?(@@beefpath) and File.exists?(@@beefpath + '/beef')

Thank you

**Comment by evilsocket** [comment]
--path "/opt/beef-project/"
