### ISSUE TITLE
Having issue using beefbox.rb

### ISSUE THREAD

**Issue by zooper26** [evilsocket/bettercap-proxy-modules#23]
Have setup beefbox.rb with correct path to bEef installation, but when I try to run the command, it keeps returning [W] undefined method `tcp_dst' for nil:NilClass. Any idea what could be causing this issue?

**Comment by evilsocket** [comment]
Please follow [these guidelines](https://www.bettercap.org/docs/contribute/) while reporting an issue.

**Comment by evilsocket** [comment]
There you are https://www.bettercap.org/blog/howto-bettercap-and-beef-framework/
