### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Silur** [evilsocket/bettercap-proxy-modules#27]
it would be nice if one could have a documentation of what can be done with the request,response parameters in the payloads

**Comment by evilsocket** [comment]
Here you [go](http://www.rubydoc.info/gems/bettercap/1.4.2/BetterCap/Proxy) :)

**Comment by Silur** [comment]
sorry I didn't notice this, thank you :+1:

**Comment by evilsocket** [comment]
np :+1:
