### ISSUE TITLE
[Feature] Replacing executable files on the fly

### ISSUE THREAD

**Issue by DarkPringles** [evilsocket/bettercap-proxy-modules#29]
Hi, first of all ... great thanks for this cool project. 

I have requested this feature in the MITMf and it was implemented successfully. Now i am often using bettercap because of its many advantages. It will be great to see a module or function in bettercap too that is able to directly replace downloaded executable files on the fly because many download portals have not implemented https. The filepwn plugin of MITMf is not very useful because the backdoored files generated with metasploit in the background are flagged by nearly any anti virus software. Replacing with own executables for example veil-evasion generated EXE-files will get more better results.

It would be nice if you can take a look at them.

Cheers, DarkPringles

**Comment by evilsocket** [comment]
👍

**Comment by vay3t** [comment]
you can use a Shellter project https://www.shellterproject.com/category/blog_news/

**Comment by MickHackEthic** [comment]
Hi Simone,
probably is just my misunderstanding about the behaviour of proxy module named http/replace_file.rb.

I have used it like this:

sudo bettercap -I wlan0 -T iptarget -X --spoofer ARP DNS --proxy-module /complete path where it is/replace_file.rb --file-extension jpg --file-replace /where this file is ( it is a jpg as well )

Than when i open chrome on any site with images it replace the whole images with the chosen one.

I have understood that this module work like this:
-if target download a file it replace it with the chosen one

Is it my misunderstanding or error using it or just I don't understand how it works? 
If you need further info just ask me.
And sorry I have lots of experience in programming but I'm new in pentest.

**Comment by DarkPringles** [comment]
Hey, 
with the --file-extension parameter you choose the target file extension you will like to replaced, not the extension of your own file. Imagine you want to replace all exe files downloaded by the victim, you have to choose --file-extension "exe" and with the  --file-replace the fill path to your own exe file. 

Hope it helps, 

Cheers.

**Comment by MickHackEthic** [comment]
Hi DarkPringles,x a lot for 
thanks a lot for super fast reply.
So if I want to replace for example all images "jpg" downloaded by the victim I have to 

choose --file-extension "jpg" and with the --file-replace the full path to my jpg file
( just for example with jpg ).

Ok I'll try like this.I'm sure it is only my mis-understanding as I said.

Thx again.

**Comment by MickHackEthic** [comment]
So DarkPringles like you said it works!! I've tried with pdf and when I try to see a pdf document from the target pc it replace it with my own pdf.

Thx again.

**Comment by DarkPringles** [comment]
Hey,  no problem. Now you understand this module. To replace all images displayed in the browser you have to choose another module. 

For PDF files for example you have the right syntax. 
Cheers.
