### ISSUE TITLE
[Bug] androidpwn.rb not working

### ISSUE THREAD

**Issue by DarkPringles** [evilsocket/bettercap-proxy-modules#30]
While testing the android module i notice that code execution is not working.
I think the problem is the javascript part.

On line 23 https://github.com/evilsocket/bettercap-proxy-modules/blob/master/http/androidpwn.rb#L23
The "command" var is initialized but not used later.
It should be used on line 26 https://github.com/evilsocket/bettercap-proxy-modules/blob/master/http/androidpwn.rb#L26 at the "exec(" statement but there is a var called "cmd".
I inserted the var name "command" instead of "cmd" and the code execution works flawless.

Can you please check this out? 

Btw: thanks for implementing my feature request (replacing executables on the fly)
very powerfull modular application!

**Comment by evilsocket** [comment]
fixed, tnx for reporting 👍
