### ISSUE TITLE
http/replace_images.rb: Line 39

### ISSUE THREAD

**Issue by GeARCraft1** [evilsocket/bettercap-proxy-modules#32]
Good Evening,
I'm trying to use the line 39 of the file http/replace_images.rb, but It doesn't work.
Running With:
`bettercap --proxy-module ReplaceImages.rb --proxy-https --httpd --httpd-path Web/`
(The Web Folder is inside the same directory than ReplaceImages.rb).
I get:
`
 _          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                                     |_| v1.5.4
http://bettercap.org/

[E] Oooops, seems like something weird occurred, please copy paste the following output and open a new issue on https://github.com/evilsocket/bettercap/issues :

[E] Platform          : x86_64-linux-gnu
[E] Ruby Version      : 2.2.3
[E] BetterCap Version : 1.5.4
[E] Command Line      : --proxy-module ReplaceImages.rb --proxy-https --httpd --httpd-path Web/
[E] Exception         : SyntaxError
[E] Message           : /root/Desktop/Hacking/Bettercap Modules/ReplaceImages/ReplaceImages.rb:39: syntax error, unexpected end-of-input, expecting keyword_end
[E] Backtrace         :

    /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /var/lib/gems/2.2.0/gems/bettercap-1.5.4/lib/bettercap/proxy/http/module.rb:51:in `load'
    /var/lib/gems/2.2.0/gems/bettercap-1.5.4/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
    /usr/lib/ruby/2.2.0/optparse.rb:1396:in `call'
    /usr/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
    /usr/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
    /usr/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
    /usr/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
    /usr/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
    /usr/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
    /var/lib/gems/2.2.0/gems/bettercap-1.5.4/lib/bettercap/options/options.rb:54:in `parse!'
    /var/lib/gems/2.2.0/gems/bettercap-1.5.4/bin/bettercap:27:in `<top (required)>'
    /usr/local/bin/bettercap:23:in `load'
    /usr/local/bin/bettercap:23:in `<main>'
`
So, What Should I Do??
Thank You, Gabriel

**Comment by evilsocket** [comment]
Update the module from this repo.

**Comment by GeARCraft1** [comment]
Nothing. Same error.

**Comment by evilsocket** [comment]
would you mind pasting here the replace_images.rb script you're using?

**Comment by GeARCraft1** [comment]
`
=begin
BETTERCAP
Author : Simone 'evilsocket' Margaritelli
Email  : evilsocket@gmail.com
Blog   : http://www.evilsocket.net/
This project is released under the GPL 3 license.
=end

# This module requires the --httpd argument being passed
# to bettercap and the --httpd-path pointing to a folder
# which contains a "hack.png" image.
class ReplaceImages < BetterCap::Proxy::HTTP::Module
  meta(
    'Name'        => 'ReplaceImages',
    'Description' => 'Replace all images on web pages.',
    'Version'     => '1.0.0',
    'Author'      => "Simone 'evilsocket' Margaritelli",
    'License'     => 'GPL3'
  )

  def initialize
    opts = BetterCap::Context.get.options.servers
    # make sure the server is running
    raise BetterCap::Error, "The ReplaceImages proxy module needs the HTTPD ( --httpd argument ) running." unless opts.httpd
    # make sure the file we need actually exists
    raise BetterCap::Error, "No hack.png file found in the HTTPD path ( --httpd-path argument ) '#{opts.httpd_path}'" \
      unless File.exist? "#{opts.httpd_path}/hack.png"

    @image_url = "\"http://#{BetterCap::Context.get.iface.ip}:#{opts.httpd_port}/hack.png\""
  end

  def on_request( request, response )
    # is it a html page?
    if response.content_type =~ /^text\/html.*/
      BetterCap::Logger.info "Replacing http://#{request.host}#{request.path} images."

      response.body.gsub! %r/["'][https:\/\/]*[^\s]+\.(png|jpg|jpeg|bmp|gif)["']/i, @image_url
    end
  end
`

**Comment by evilsocket** [comment]
you're missing the last **end** statement for some reason, the actual code is here https://github.com/evilsocket/bettercap-proxy-modules/blob/master/http/replace_images.rb
