### ISSUE TITLE
tcp proxy module that handle search/replace based on regexp

### ISSUE THREAD

**Issue by fpietrosanti** [evilsocket/bettercap-proxy-modules#41]
This ticket is to implement a tcp proxy module that handle search/replace of traffic ascii string based on regular expression (that should be loaded from a file or either from command line).

A tcp proxy module like that would bring bettercap to the same functionality level of netsed/nfqSed (Reference: https://eclecticismnow.wordpress.com/2016/12/11/sostituire-stringhe-di-testo-che-passano-sulla-rete/)

**Comment by evilsocket** [comment]
You'll be able to use this module on the next bettercap release.

**Comment by gavz** [comment]
Error : [E] /bettercap-proxy-modules/tcp/netsed.rb is not a valid bettercap proxy module.

bettercap v1.6.1b & bettercap v1.6.0
