### ISSUE TITLE
Enhancement suggestion for noscroll.rb

### ISSUE THREAD

**Issue by laozi999** [evilsocket/bettercap-proxy-modules#44]
This proxy module spawns a full screen div on top of the page preventing the user from scrolling/clicking. Someone with basic dev knowledge could figure out that it takes a simple right click > inspect element and a simple press on the delete button to get rid of this blockage.

What I'm suggesting is adding the following CSS to add another layer of legitimacy to this attack, which might make the user believe it is indeed time for an 'update'.

`html, body { pointer-events: none !imporant; }`

Update: this CSS also disables a user to right-click on the page.

**Comment by evilsocket** [comment]
why don't u send a pull request then? :)

**Comment by laozi999** [comment]
Woah, I've taken a long break from github!

Working on it ;)

**Comment by laozi999** [comment]
Here it is :)

https://github.com/evilsocket/bettercap-proxy-modules/pull/50
