### ISSUE TITLE
download_redirect.rb enhancement suggestion(s)

### ISSUE THREAD

**Issue by laozi999** [evilsocket/bettercap-proxy-modules#51]
I wish I was more experienced with Ruby, so I might take (too) long to finish this myself, but...

I'm not sure if it's already the case, but allowing multiple types of files separated by a comma (EXE,PDF,APK,ZIP,DEB, ...) and having these file types in a local folder could allow a much higher success rate.

So for example:

```
/bettercap-proxy-modules-master/http/download_redirect/file.exe
/bettercap-proxy-modules-master/http/download_redirect/file.pdf
/bettercap-proxy-modules-master/http/download_redirect/file.apk
/bettercap-proxy-modules-master/http/download_redirect/file.zip
/bettercap-proxy-modules-master/http/download_redirect/file.deb
```

Now the cool thing would be, once the victim requests a download (Sublime Text for example), bettercap grabs the file name from the URL (http ://download.sublimetext.com/**sublime-text_build-3126_amd64.deb**), then finds the file with a **.deb** extension in the proxy modules, renames it to **sublime-text_build-3126_amd64.deb**, and then sends the malicious file instead. 

The victim would have no idea! :smile:

**Comment by alternatexp** [comment]
yes please make it work like this!!

**Comment by laozi999** [comment]
Could be called download_autopwn ;)

**Comment by evilsocket** [comment]
@laozi999 my thoughts is that the modules are open source, which means you don't have to wait for me in order to get this, just do it yourself! :P
