### ISSUE TITLE
Changing post request

### ISSUE THREAD

**Issue by lalalaporo** [evilsocket/bettercap-proxy-modules#52]
Hi,

My set up got 1 web page and a server. The webpage constantly POST its own status to the server and the server will reply a http ok afterwards with some other detail. What I want to do at the minute is be able to intercept the POST packet and change it.

```
@pressed = true # just for demonstrate the function
def on_pre_request(request)
                if request.post? and !request.body.nil? and !request.body.empty? then
                        if @pressed == true
                                BetterCap::Logger.info "Button pressed"
                                request.body.setbyte(0,0x01)           #Just for demonstration to set byte to 0x01, the actual thing that I wanted to do is the five commented line below
                                #request.body.setbyte(32,0x02)         
                                #request.body.setbyte(37,0x1d)
                                #request.body.setbyte(38,0x00)
                                #request.body.setbyte(39,0x5b)
                                #request.body.setbyte(40,0x00)
                                @pressed = false
                        else
                        end
                end
        end
```

I have tried on_request (while the rest of the code stay the same), the packet has not been changed.
And when I think it would make sense and tried the on_pre_request, there are error comes up from the streamer.rb and strip.rb. Have I done anything wrong here?

BTW just want to mention one of my set up got a very similar, if not same, issue as https://github.com/evilsocket/bettercap/issues/187  , while the other set up, with different switch and laptops, stay fine (But I have to manually delete the arp in my machines after ctrl+c or it will not run the next time). Anyway that is not the point of this question.

bettercap 1.6.1b
packetfu v 1.1.11

Thanks

**Comment by evilsocket** [comment]
On the `on_pre_request` method, you need to return a Response object, otherwise the request will be normally executed and both the Request and Response objects will be passed to the `on_request` handler.

**Comment by lalalaporo** [comment]
Thanks.

I am kinda confuse on the request and response.
Is it like the packet from client go through on_pre_request, and the server returns a reponse on which the request and response go thorugh on_request before reaching client?
I feel like I am misunderstanding the whole thing? 

Anway, I'm trying to return a Response.new but it seems wrong. Is it like I have to copy the request to the response? But the field for the request object and response object seem different.

**Comment by lalalaporo** [comment]
I'm look at the streamer.rb. 
I'm thinking like the entry point of the packet is the handle method.
And then the on_pre_request is called in the process method, on which the response is gonna be nil if nil is returned from on_pre_request and it will call do_POST in my case. Assuming the do_POST is sending out the POST packet to the server, then this is what I wanted. And finally I can mess with the http ok from the server later.
But it does not seem to do anything if it goes this route. And I thinking it too simplified or even wrong?

I am sorry and thanks for your time
